name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - prod

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
        
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install

            # 환경 변수 설정 (GitHub Secrets에서 불러오기)
            - name: Create .env file
              run: |
                echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
                echo "TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}" >> .env
                echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
                echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
                echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
                echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
                echo "KAKAO_RESTAPI_KEY=${{ secrets.KAKAO_RESTAPI_KEY }}" >> .env
                echo "KAKAO_REDIRECT_URL=${{ secrets.KAKAO_REDIRECT_URL }}" >> .env
                echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
                echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env
                echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env
                echo "REFRESH_TOKEN_EXPIRE_DAYS=${{ secrets.REFRESH_TOKEN_EXPIRE_DAYS }}" >> .env

    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            # AWS 자격 증명 설정
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-region: ${{ secrets.AWS_REGION }}
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            # 퍼블릭 ECR 로그인을 위한 설정
            - name: Log in to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v1

            # Docker 이미지 빌드 및 태깅
            - name: Build Docker image
              run: |
                # Docker 이미지 빌드
                docker build -t wellnessapp:${{ github.sha }} .

                # GitHub SHA로 태그
                docker tag wellnessapp:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}

                # latest로 태그
                docker tag wellnessapp:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}:latest

            # Docker 이미지 푸시
            - name: Push Docker image to ECR
              run: |
                # GitHub SHA 태그로 푸시
                docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}

                # latest 태그로 푸시
                docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/prod'

        steps:
            - name: Deploy to ECS
              run: |
                aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
